set(CMAKE_ASM_OUTPUT_EXTENSION .rel)
set(CMAKE_ASMSDAS8051_OUTPUT_EXTENSION .rel)
set(CMAKE_ASM_OUTPUT_EXTENSION_REPLACE 1)


set(CMAKE_STATIC_LIBRARY_PREFIX "")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".lib")
set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".lib")
set(CMAKE_IMPORT_LIBRARY_PREFIX )
set(CMAKE_IMPORT_LIBRARY_SUFFIX )
set(CMAKE_EXECUTABLE_SUFFIX ".hex")
set(CMAKE_LINK_LIBRARY_SUFFIX ".lib")
set(CMAKE_DL_LIBS "")

if(NOT DEFINED CMAKE_C_FLAGS_INIT)
    set(CMAKE_C_FLAGS_INIT "")
endif()

if(NOT DEFINED CMAKE_ASM_FLAGS_INIT)
    set(CMAKE_ASM_FLAGS_INIT "")
endif()

if(NOT DEFINED CMAKE_EXE_LINKER_FLAGS_INIT)
    set (CMAKE_EXE_LINKER_FLAGS_INIT "")
endif()

set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <FLAGS> <OBJECT> <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE "${CMAKE_ASM_COMPILER_LINKER} <CMAKE_ASM_LINK_FLAGS> <TARGET> <OBJECTS>")

set(CMAKE_ASM_CREATE_STATIC_LIBRARY
        "\"${CMAKE_COMMAND}\" -E remove <TARGET>"
        "<CMAKE_AR> -rc <TARGET>  <OBJECTS> ")

set(CMAKE_ASM_CREATE_SHARED_LIBRARY "")
set(CMAKE_ASM_CREATE_MODULE_LIBRARY "")